baseURL = 'https://socia-data-visualization.netlify.app/'
languageCode = 'en-us'
title = 'Trees in New York!'
theme = "hyde"

[params]
  description = "A study on the impact of trees on air quality in New York"
  themeColor = "theme-base-0b"
  authorImage = "/images/avatar.jpg"

